- in configure_campsite(): when running configure check for errors - updated some messages

diff --git a/.install_conf/install_functions b/.install_conf/install_functions
--- a/.install_conf/install_functions
+++ b/.install_conf/install_functions
@@ -52,7 +52,8 @@ if [ "$cc_interactive" = "--interactive" ]; then
 configure_install $cc_upgrade
 [ $? -ne 0 ] && echo "Error configuring install parameters" && exit 1
 install_conf --set
-. $INSTALL_CONF/../configure --define_start_env &> /dev/null
+. $"$INSTALL_CONF/../configure" --define_start_env &> /dev/null
+[ $? -ne 0 ] && echo "Error configuring install environment" && exit 1
 
 export MODULES_LIST="DATABASE PARSER EVENT_HANDLERS SEARCH_ENGINE ADMIN_INTERFACE"
 echo "Please wait while checking modules configuration..."
@@ -77,8 +78,8 @@ for cc_mod in $NEED_CONFIG_MODULES; do
 done
 cc_err_msg=""
 while true; do
-#    clear
-    echo "The forward list shows modules that need to be configured."
+    echo -e "\nThe following list shows modules that are configurable."
+    echo "Modules not shown in this list are not configurable at this stage."
     echo "Modules checked with X have a valid configuration."
     cc_index=1
     all_ok=true
@@ -124,8 +125,7 @@ while true; do
 done
 choice_yn "\nCampsite configuration is completed. Do you want to review it?" Y
 if [ "$choice" = "Y" ]; then
-    clear
-    echo "Install configuration"
+    echo -e "\nInstall configuration"
     install_conf
     echo -e "\nTo continue press ENTER"
     read
