fixed ticket:2269 - Campsite doesn't compile on 64 bit systems

diff --git a/campsite/install_conf/check4_functions b/campsite/install_conf/check4_functions
--- a/campsite/install_conf/check4_functions
+++ b/campsite/install_conf/check4_functions
@@ -741,7 +741,7 @@ return 0
 check4_libz()
 {
 is_checked libz && return 0
-check4_file libz.so --file --path "/usr/lib:/usr/local/lib"
+check4_file libz.so --file --path "/usr/lib:/usr/local/lib:/usr/lib64"
 result=$? && [ $result -ne 0 ] && output="Could not find z compression library. Please install zlib1-devel package." && return 1
 export LIBZ=$file_path
 set_checked libz
@@ -763,7 +763,7 @@ if [ $OPENBSD -eq 1 ]; then
     export LIBCRYPT=
     export LIBCRYPT_LINK=
 else
-    check4_file libcrypt.so --file --path "/usr/lib:/usr/local/lib"
+    check4_file libcrypt.so --file --path "/usr/lib:/usr/local/lib:/usr/lib64:/usr/local/lib64"
     result=$? && [ $result -ne 0 ] && output="Could not find crypt library. Please install glibc-devel package." && return 1
     export LIBCRYPT=$file_path
     export LIBCRYPT_LINK=-lcrypt
@@ -783,8 +783,15 @@ return 0
 check4_libmysqlclient()
 {
 is_checked libmysqlclient && return 0
-check4_file libmysqlclient.a --file --path "/usr/lib:/usr/lib/mysql:/usr/local/mysql:/usr/local/lib:/usr/local/lib/mysql:/usr/local/mysql/lib:/usr/lib64/mysql"
-result=$? && [ $result -ne 0 ] && return 1
+output=`check4_file libmysqlclient.a --file --path "/usr/lib:/usr/lib/mysql:/usr/local/mysql:/usr/local/lib:/usr/local/lib/mysql:/usr/local/mysql/lib:/usr/lib64/mysql"`
+result=$?
+if [ $result -ne 0 ]; then
+    output=`check4_file libmysqlclient_r.a --file --path "/usr/lib:/usr/lib/mysql:/usr/local/mysql:/usr/local/lib:/usr/local/lib/mysql:/usr/local/mysql/lib:/usr/lib64/mysql"`
+    result=$? && [ $result -ne 0 ] && echo "Could not find libmysqlclient library. Please install mysqlclient-devel package." && return 1
+    check4_file libmysqlclient_r.a --file --path "/usr/lib:/usr/lib/mysql:/usr/local/mysql:/usr/local/lib:/usr/local/lib/mysql:/usr/local/mysql/lib:/usr/lib64/mysql"
+else
+    check4_file libmysqlclient.a --file --path "/usr/lib:/usr/lib/mysql:/usr/local/mysql:/usr/local/lib:/usr/local/lib/mysql:/usr/local/mysql/lib:/usr/lib64/mysql"
+fi
 export LIBMYSQLCLIENT=$file_path
 export LIBMYSQLCLIENT_PATH=`cut_last_dirs $LIBMYSQLCLIENT 1`
 check4_gpp
@@ -829,7 +836,7 @@ if [ $BSD -eq 1 ]; then
 	export PTHREAD_LINK=-pthread
 	return 0
 fi
-check4_file libpthread.so --file --path "/usr/lib:/usr/local/lib"
+check4_file libpthread.so --file --path "/usr/lib:/usr/local/lib:/usr/lib64:/usr/local/lib64"
 result=$? && [ $result -ne 0 ] && return 1
 export LIBPTHREAD=$file_path
 export LIBPTHREAD_PATH=`cut_last_dirs $LIBPTHREAD 1`
@@ -895,7 +902,7 @@ set_checked libnsl
 libcnames="libc.a libc_r.a libc.so libc_r.so"
 
 # list of possible lisc directories
-libcdirs="/usr/lib:/lib"
+libcdirs="/usr/lib:/usr/lib64:/lib"
 
 # FUNCTION: check4_gethostbyaddr_r
 # Description:
@@ -1034,6 +1041,22 @@ set_checked php_gd
 return 0
 }
 # END OF check4_php_gd
+
+# FUNCTION: check4_php_session
+# Description: check if php session module was installed
+# Parameters: none
+# Variables set:
+#	output - error message (if any)
+check4_php_session()
+{
+is_checked php_session && return 0
+check4_php_cli || return 1
+"$PHP" -q "$INSTALL_CONF/php_session_exists.php"
+[ $? -ne 0 ] && output="PHP session library was not installed. Please install it." && return 1
+set_checked php_session
+return 0
+}
+# END OF check4_php_session
 
 # FUNCTION: check4_convert
 # Description: check if ImageMagic package was installed
