update to ticket:2614 - deb install package does not install with install/index.php

diff --git a/packaging/debian/postrm b/packaging/debian/postrm
--- a/packaging/debian/postrm
+++ b/packaging/debian/postrm
@@ -1,16 +1,58 @@
 #!/bin/sh
+# postrm script for Campsite 
+#
+# see: dh_installdeb(1)
 
-NAME="campsite"
+set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 case "$1" in
-
-  purge)
-    rm -rf /etc/campsite
-    rm -rf /usr/share/campsite
+    purge)
+	#dirname=`cat /etc/campsite/dirname|sed -e 's/,  */ /g'`
+	#rm -rf $dirname
+        rm -rf /etc/campsite
+        rm -rf /usr/share/campsite
+    ;;
+    remove)
+	if [ -x /usr/share/wwwconfig-common/restart.sh ] 
+	then
+	. /usr/share/wwwconfig-common/restart.sh
+	fi
+			
+    ;;
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
     ;;
 
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+# Automatically added by dh_installdebconf
+if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
+	. /usr/share/debconf/confmodule
+	db_purge
+fi
+# End automatically added section
 
 
 exit 0
+
+
