- run check4_php_cli at the start of the script: we need it - use global variable PHP when calling php CLI interpretor (for cases when php is not in the path) - deleted obsolete messages - in prepare_PARSER_env() function: verify if check4 functions returned error

diff --git a/campsite/.install_conf/conf_functions b/campsite/.install_conf/conf_functions
--- a/campsite/.install_conf/conf_functions
+++ b/campsite/.install_conf/conf_functions
@@ -2,6 +2,9 @@
 
 . ${INSTALL_CONF}/check4_functions
 
+check4_php_cli
+[ $? -ne 0 ] && echo $output && exit 1
+
 ###########################################################
 ## Functions for manipulating configuration variables
 ###########################################################
@@ -244,12 +247,12 @@ action="print"
 configurable_modules=""
 modules=`modules_list $*`
 for m in $modules; do
-    conf_file=`cd "$INSTALL_CONF"; php -q module_conf_file.php "$m"`
+    conf_file=`cd "$INSTALL_CONF"; $"$PHP" -q module_conf_file.php "$m"`
     if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
 	continue
     fi
     configurable_modules="$configurable_modules $m"
-    mod_conf=`cd "$INSTALL_CONF"; php -q export_conf.php "$m"`
+    mod_conf=`cd "$INSTALL_CONF"; $"$PHP" -q export_conf.php "$m"`
     if [ $? -ne 0 ]; then
         echo "$mod_conf"
         return 1
@@ -257,7 +260,7 @@ for m in $modules; do
     if [ "$action" = "print" ]; then
 	echo "$mod_conf" | cut -f 2 -d " "
     fi
-    mod_param_list=`cd "$INSTALL_CONF"; php -q export_module_params.php "$m"`
+    mod_param_list=`cd "$INSTALL_CONF"; $"$PHP" -q export_module_params.php "$m"`
     if [ $? -ne 0 ]; then
         echo "$mod_param_list"
         return 1
@@ -295,11 +298,11 @@ action="print"
 [ "$1" = "--set" ] && action="set" && shift 1
 [ "$1" = "--reset" ] && action="reset" && shift 1
 [ "$1" = "--unset" ] && action="unset" && shift 1
-conf_file=`cd "$INSTALL_CONF"; php -q module_conf_file.php "install"`
+conf_file=`cd "$INSTALL_CONF"; $"$PHP" -q module_conf_file.php "install"`
 if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
     return 1
 fi
-inst_conf=`cd "$INSTALL_CONF"; php -q export_conf.php "install"`
+inst_conf=`cd "$INSTALL_CONF"; $"$PHP" -q export_conf.php "install"`
 if [ $? -ne 0 ]; then
     echo "$inst_conf"
     return 1
@@ -307,7 +310,7 @@ fi
 if [ "$action" = "print" ]; then
     echo "$inst_conf" | cut -f 2 -d " "
 fi
-inst_param_list=`cd "$INSTALL_CONF"; php -q export_module_params.php "install"`
+inst_param_list=`cd "$INSTALL_CONF"; $"$PHP" -q export_module_params.php "install"`
 if [ $? -ne 0 ]; then
     echo "$inst_param_list"
     return 1
@@ -340,14 +343,12 @@ return 0
 # Description: prepare the environment for DATABASE module
 # Parameters: none
 # Variables set:
-#	MYSQL_CONNECT - mysql_connect binary full path
+#	none
 prepare_DATABASE_env()
 {
 in_list DATABASE $PREPARED_MOD_ENV && return 0
-output_err="Error preparing environment for DATABASE module."
-echo "*** Preparing DATABASE environment..."
+echo "*** Preparing DATABASE environment...OK"
 add_to_list_var DATABASE PREPARED_MOD_ENV
-echo "DATABASE environment OK"
 return 0
 }
 # END OF prepare_DATABASE_env
@@ -359,11 +360,14 @@ return 0
 prepare_PARSER_env()
 {
 in_list PARSER $PREPARED_MOD_ENV && return 0
+echo -n "*** Preparing PARSER environment..."
 check4_gethostbyaddr_r
+[ $? -ne 0 ] && echo "ERROR" && return 1
 check4_gethostbyname_r
+[ $? -ne 0 ] && echo "ERROR" && return 1
 check4_getservbyname_r
-output_err="Error preparing environment for PARSER module."
-echo -e "*** Preparing PARSER environment...OK"
+[ $? -ne 0 ] && echo "ERROR" && return 1
+echo "OK"
 add_to_list_var PARSER PREPARED_MOD_ENV
 return 0
 }
@@ -403,7 +407,6 @@ return 0
 prepare_SEARCH_ENGINE_env()
 {
 in_list SEARCH_ENGINE $PREPARED_MOD_ENV && return 0
-output_err="Error preparing environment for SEARCH_ENGINE module."
 echo -e "*** Preparing SEARCH_ENGINE environment...OK"
 add_to_list_var SEARCH_ENGINE PREPARED_MOD_ENV
 return 0
@@ -417,7 +420,6 @@ return 0
 prepare_ADMIN_INTERFACE_env()
 {
 in_list ADMIN_INTERFACE $PREPARED_MOD_ENV && return 0
-output_err="Error preparing environment for ADMIN_INTERFACE module."
 echo -e "*** Preparing ADMIN_INTERFACE environment...OK"
 add_to_list_var ADMIN_INTERFACE PREPARED_MOD_ENV
 return 0
@@ -431,7 +433,6 @@ return 0
 prepare_install_env()
 {
 output_err="Error preparing install environment."
-echo -e -n "Preparing install environment..."
 export OLD_CAMPSITE_REGISTER=/etc/campsite.reg
 export CHECKED_DEPENDENCIES=""
 export CHECKED_MODULES=""
@@ -449,7 +450,6 @@ for mod in $MODULES_LIST; do
 done
 set_need_config_modules
 [ $? -ne 0 ] && echo $output_err && return 1
-echo "OK"
 return 0
 }
 # END OF prepare_install_env
@@ -527,7 +527,7 @@ fi
 if [ "$1" != "--config" ]; then
     return 0
 fi
-conf_file=`cd "$INSTALL_CONF"; php -q module_conf_file.php "$module"`
+conf_file=`cd "$INSTALL_CONF"; $"$PHP" -q module_conf_file.php "$module"`
 if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
     echo "Module $module is not configurable"
     return 1
@@ -765,7 +765,7 @@ return $result
 set_module_config()
 {
 module=$1
-module_file=`cd "$INSTALL_CONF"; php -q module_conf_file.php "$module"`
+module_file=`cd "$INSTALL_CONF"; $"$PHP" -q module_conf_file.php "$module"`
 tmp_file=".$$.$module_file"
 module_name=`echo "$module_file" | cut -f 1 -d "_"`
 if [ "$module_name" != "install" ]; then
@@ -775,7 +775,7 @@ if [ "$module_name" != "install" ]; then
 	return 1
     fi
 fi
-module_vars=`cd "$INSTALL_CONF"; php -q export_module_params.php "$module"`
+module_vars=`cd "$INSTALL_CONF"; $"$PHP" -q export_module_params.php "$module"`
 echo -e "<?php\n" > $tmp_file;
 vars_list_str=""
 for var in $module_vars; do
@@ -911,7 +911,7 @@ module_check=$1
 shift 1
 message=""
 while true; do
-    module_config_menu "$module"
+    echo " " && module_config_menu "$module"
     echo $message
     echo -n -e "Option: "
     read -r option
@@ -966,7 +966,7 @@ ci_upgrade=""
 [ "$1" = "--upgrade" ] && ci_upgrade="--upgrade"
 message=""
 while true; do
-    install_config_menu
+    echo " " && install_config_menu
     echo $message
     echo -n -e "Option: "
     read -r option
