major changes related to feature 247: Improve management of multiple instances of CAMPSITE on a single server

diff --git a/campsite/.install_conf/conf_functions b/campsite/.install_conf/conf_functions
--- a/campsite/.install_conf/conf_functions
+++ b/campsite/.install_conf/conf_functions
@@ -87,7 +87,7 @@ return 0
 # Variables set: none
 unset_env_vars()
 {
-unset SELECTED_MODULES
+unset MODULES_LIST
 unset IMPLEMENTATION_PARTS
 unset SUPPLEMENTAL_PARTS
 unset CAMPSITE_VERSION
@@ -121,7 +121,7 @@ dependent_on()
 validate_module $1
 [ $? -ne 0 ] && return 1
 grep -w "@$1" ${INSTALL_CONF}/.modules.dep | cut -f 1 -d ":"
-return $?
+return 1
 }
 # END OF dependent_on
 
@@ -156,7 +156,7 @@ preconf_modules()
 validate_module $1
 [ $? -ne 0 ] && return 1
 grep -w "^$1" ${INSTALL_CONF}/.modules.dep | cut -f 3 -d ":"
-return $?
+return 1
 }
 # END OF preconf_modules
 
@@ -274,77 +274,37 @@ action="print"
 [ "$1" = "--unset" ] && action="unset" && shift 1
 configurable_modules=""
 modules=`modules_list $*`
-mc=`cat ${INSTALL_CONF}/.modules.conf`
-state=init_mod
-for w in $mc; do
-    case $state in
-    init_mod)
-	mod_name=""
-	print_conf=false
-	attr_list=""
-	attr_desc=""
-	attr_name=""
-	if [ "$w" = "[" ]; then
-	    state=read_mod_name
-	fi ;;
-    read_mod_name)
-	mod_name=$w
-	configurable_modules="$configurable_modules $mod_name"
-	echo $modules | grep $mod_name &> /dev/null
-	[ $? -eq 0 ] && print_conf=true
-	state=read_attr_name ;;
-    read_attr_name)
-	if [ "$w" = "{" ]; then
-	    state=read_attr_desc
-	elif [ "$w" = "]" ]; then
-	    state=init_mod
-	    [ "$action" = "print" ] && [ "$print_conf" = "true" ] && echo -e $attr_list
-	else
-	    [ "$attr_list" != "" ] && attr_list="$attr_list\n"
-	    attr_name=$w
-	    attr_list="$attr_list${mod_name}_$attr_name="
-	    attr_val=""
-	    state=read_attr_val
-	fi ;;
-    read_attr_val)
-	attr_desc=""
-	if [ "$w" = "{" ]; then
-	    attr_list="$attr_list$attr_val"
-	    [ "$action" = "set" ] && [ "$print_conf" = "true" ] && export ${mod_name}_$attr_name="`echo $attr_val`"
-	    [ "$action" = "unset" ] && [ "$print_conf" = "true" ] && unset ${mod_name}_$attr_name
-	    state=read_attr_desc
-	else
-	    [ "$attr_val" != "" ] && attr_val="$attr_val $w"
-	    [ "$attr_val" = "" ] && attr_val="$w"
-	fi
-	;;
-    read_attr_desc)
-	if [ "$w" = "}" ]; then
-	    attr_list="$attr_list # $attr_desc"
-	    state=read_attr_name
-	else
-	    attr_desc="$attr_desc $w"
-	fi
-	;;
-    *)
-	echo "Internal error (invalid state $state)"
-	exit 1 ;;
-    esac
+for m in $modules; do
+    conf_file=`cd "$INSTALL_CONF"; php module_conf_file.php "$m"`
+    if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
+	continue
+    fi
+    configurable_modules="$configurable_modules $m"
+    mod_conf=`cd "$INSTALL_CONF"; php export_conf.php "$m"`
+    if [ $? -ne 0 ]; then
+        echo "$mod_conf"
+        return 1
+    fi
+    if [ "$action" = "print" ]; then
+	echo "$mod_conf" | cut -f 2 -d " "
+    fi
+    mod_param_list=`cd "$INSTALL_CONF"; php export_module_params.php "$m"`
+    if [ $? -ne 0 ]; then
+        echo "$mod_param_list"
+        return 1
+    fi
+    if [ "$action" = "set" ]; then
+	$mod_conf
+    fi
+    if [ "$action" = "unset" ]; then
+	for p in $mod_param_list; do
+	    unset $p
+	done
+    fi
 done
 return 0
 }
 # END OF modules_conf
-
-# FUNCTION: selected_modules
-# Description: prints the list of selected modules
-# Parameters: none
-# Variables set: none
-selected_modules()
-{
-cat ${INSTALL_CONF}/.inst.modules
-return 0
-}
-# END OF selected_modules
 
 # FUNCTION: install_conf
 # Description: prints the install configuration
@@ -357,62 +317,31 @@ install_conf()
 action="print"
 [ "$1" = "--set" ] && action="set" && shift 1
 [ "$1" = "--unset" ] && action="unset" && shift 1
-mc=`cat ${INSTALL_CONF}/.inst.conf | grep -v ^#`
-attr_list=""
-attr_desc=""
-attr_name=""
-state=init
-for w in $mc; do
-    case $state in
-    init)
-	if [ "$w" = "[" ]; then
-	    state=read_attr_name
-	fi ;;
-    read_attr_name)
-	if [ "$w" = "{" ]; then
-	    state=read_attr_desc
-	elif [ "$w" = "]" ]; then
-	    state=end
-	else
-	    [ "$attr_list" != "" ] && attr_list="$attr_list\n"
-	    attr_name=$w
-	    attr_list="$attr_list$attr_name="
-	    attr_val=""
-	    state=read_attr_val
-	fi ;;
-    read_attr_val)
-	attr_desc=""
-	if [ "$w" = "{" ]; then
-	    [ "$action" = "set" ] && export $attr_name="`echo $attr_val`"
-	    [ "$action" = "unset" ] && unset $attr_name
-	    attr_list="$attr_list$attr_val"
-	    state=read_attr_desc
-	elif [ "$w" = "]" ]; then
-	    attr_list="$attr_list$attr_val"
-	    state=end
-	else
-	    [ "$attr_val" != "" ] && attr_val="$attr_val $w"
-	    [ "$attr_val" = "" ] && attr_val="$w"
-	fi
-	;;
-    read_attr_desc)
-	if [ "$w" = "}" ]; then
-	    attr_list="$attr_list # $attr_desc"
-	    state=read_attr_name
-	elif [ "$w" = "]" ]; then
-	    state=end
-	else
-	    attr_desc="$attr_desc $w"
-	fi
-	;;
-    end)
-	;;
-    *)
-	echo "Internal error (invalid state $state)"
-	exit 1 ;;
-    esac
-done
-[ "$action" = "print" ] && echo -e $attr_list
+conf_file=`cd "$INSTALL_CONF"; php module_conf_file.php "install"`
+if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
+    continue
+fi
+inst_conf=`cd "$INSTALL_CONF"; php export_conf.php "install"`
+if [ $? -ne 0 ]; then
+    echo "$inst_conf"
+    return 1
+fi
+if [ "$action" = "print" ]; then
+    echo "$inst_conf" | cut -f 2 -d " "
+fi
+inst_param_list=`cd "$INSTALL_CONF"; php export_module_params.php "install"`
+if [ $? -ne 0 ]; then
+    echo "$inst_param_list"
+    return 1
+fi
+if [ "$action" = "set" ]; then
+    $inst_conf
+fi
+if [ "$action" = "unset" ]; then
+    for p in $inst_param_list; do
+        unset $p
+    done
+fi
 return 0
 }
 # END OF install_conf
@@ -525,22 +454,23 @@ prepare_install_env()
 {
 output_err="Error preparing install environment."
 echo -e -n "Preparing install environment..."
-export CAMPSITE_REGISTER=$PREFIX/etc/campsite.reg
+export OLD_CAMPSITE_REGISTER=/etc/campsite.reg
 export CHECKED_DEPENDENCIES=""
 export CHECKED_MODULES=""
 export CONFIGURED_MODULES=""
 export INSTALL_CONFIGURED="no"
 export PREPARED_MOD_ENV=""
-selected_modules=`selected_modules`
+modules_list=`modules_list`
 [ $? -ne 0 ] && echo "Error reading selected modules" && exit 1
-export SELECTED_MODULES=$selected_modules
+export MODULES_LIST=$modules_list
 export IMPLEMENTATION_PARTS=""
 export SUPPLEMENTAL_PARTS=""
-for mod in $SELECTED_MODULES; do
+for mod in $MODULES_LIST; do
     set_module_parts $mod
     [ $? -ne 0 ] && echo $output_err && return 1
 done
 set_need_config_modules
+[ $? -ne 0 ] && echo $output_err && return 1
 echo "OK"
 return 0
 }
@@ -579,8 +509,9 @@ return 0
 set_need_config_modules()
 {
 modules_conf --set
+[ $? -ne 0 ] && return 1
 NEED_CONFIG_MODULES=""
-for ncm_mod in $SELECTED_MODULES; do
+for ncm_mod in $MODULES_LIST; do
     ncm_preconf_mod=`preconf_modules $ncm_mod`
     for ncm_pmod in $ncm_preconf_mod; do
 	in_list $ncm_mod $configurable_modules && add_to_list_var $ncm_pmod NEED_CONFIG_MODULES
@@ -588,6 +519,7 @@ for ncm_mod in $SELECTED_MODULES; do
     in_list $ncm_mod $configurable_modules && add_to_list_var $ncm_mod NEED_CONFIG_MODULES
 done
 export NEED_CONFIG_MODULES
+return 0
 }
 # END OF set_need_config_modules
 
@@ -618,8 +550,8 @@ fi
 if [ "$1" != "--config" ]; then
     return 0
 fi
-grep -w -e "$module" ${INSTALL_CONF}/.modules.conf &> /dev/null
-if [ $? -ne 0 ]; then
+conf_file=`cd "$INSTALL_CONF"; php module_conf_file.php "$module"`
+if [ ! -f "$INSTALL_CONF/$conf_file" ]; then
     echo "Module $module is not configurable"
     return 1
 fi
@@ -675,28 +607,10 @@ return 0
 #	output - output error message (if any)
 check_DATABASE_config()
 {
-dc_upgrade=false
-while [ "$1" != "" ]; do
-    case $1 in
-    --upgrade) dc_upgrade=true ;;
-    esac
-    shift 1
-done
 in_list DATABASE $CHECKED_MODULES && return 0
 echo -n "Testing database configuration..."
-database=""
-grep -w DATABASE ${INSTALL_CONF}/.inst.modules &> /dev/null
-[ $? -ne 0 ] && database="-d $DATABASE_NAME"
-output=`$MYSQL_CONNECT $database $DATABASE_SERVER $DATABASE_PORT $DATABASE_USER "$DATABASE_PASSWORD"`
-result=$?
-if [ $result -ne 0 ]; then
-    echo -e "ERROR\n$output"
-    return 1
-fi
-mysql_version=$output
-output=""
-echo "OK"
 add_to_list_var DATABASE CHECKED_MODULES
+echo "OK"
 return 0
 }
 # END OF check_DATABASE_config
@@ -709,24 +623,6 @@ check_PARSER_config()
 {
 in_list PARSER $CHECKED_MODULES && return 0
 echo -n "Testing PARSER configuration..."
-if [ "$PARSER_ALLOWED_HOSTS" = "" ]; then
-    echo -e "ERROR\nPARSER_ALLOWED_HOSTS is empty."
-    return 1
-fi
-admin_selected=false
-in_list ADMIN_INTERFACE $SELECTED_MODULES && admin_selected=true
-if [ "$admin_selected" = "false" ] && ( [ "$PARSER_ALLOWED_HOSTS" = "localhost" ] || [ "$PARSER_ALLOWED_HOSTS" = "127.0.0.1" ] ); then
-    echo -e "ERROR\nADMIN_INTERFACE module is not selected for local install but allowed host is localhost."
-    return 1
-fi
-for ipa in $PARSER_ALLOWED_HOSTS; do
-    ping "$ipa" -c 1 &> /dev/null
-    ping_res=$?
-    if [ $ping_res -ne 0 ]; then
-        echo -e "ERROR\nInvalid IP address $ipa!"
-	return 1
-    fi
-done
 acp=""
 if [ "$APACHE_CONF_PATH" != "" ]; then
     acp="--apache_conf_path $APACHE_CONF_PATH"
@@ -737,10 +633,6 @@ if [ "$APACHE_BIN_PATH" != "" ]; then
 fi
 check4_apache $1 $acp $abp
 [ $? -ne 0 ] && return 1
-if [ "$PARSER_USER" != "$APACHE_USER" ] || [ "$PARSER_GROUP" != "$APACHE_GROUP" ]; then
-    echo -e "ERROR\nParser process user/group is not the same as apache user/group."
-    return 1
-fi
 add_to_list_var PARSER CHECKED_MODULES
 echo "OK"
 return 0
@@ -756,16 +648,6 @@ check_EVENT_HANDLERS_config()
 {
 in_list EVENT_HANDLERS $CHECKED_MODULES && return 0
 echo -n "Testing EVENT_HANDLERS configuration..."
-user_name=`id -u -n`
-host_name=`hostname`
-user_email="$user_name@$host_name"
-output=`$SMTP_WRAPPER $user_email -r $user_email -s $EVENT_HANDLERS_SMTP_SERVER --test`
-result=$?
-if [ $result -ne 0 ]; then
-    echo -e "ERROR\n$output"
-    return 1
-fi
-output=""
 add_to_list_var EVENT_HANDLERS CHECKED_MODULES
 echo "OK"
 return 0
@@ -778,8 +660,10 @@ return 0
 # Variables set: none
 check_SEARCH_ENGINE_config()
 {
+in_list SEARCH_ENGINE $CHECKED_MODULES && return 0
+echo -n "Testing SEARCH_ENGINE configuration..."
 add_to_list_var SEARCH_ENGINE CHECKED_MODULES
-echo "Nothing to test for SEARCH_ENGINE configuration"
+echo "OK"
 return 0
 }
 # END OF check_SEARCH_ENGINE_config
@@ -790,24 +674,10 @@ return 0
 # Variables set: none
 check_ADMIN_INTERFACE_config()
 {
-if ! in_list PARSER $SELECTED_MODULES; then
-    echo "Nothing to test for ADMIN_INTERFACE configuration"
-    add_to_list_var ADMIN_INTERFACE CHECKED_MODULES
-    return 0
-fi
+in_list ADMIN_INTERFACE $CHECKED_MODULES && return 0
 echo -n "Testing ADMIN_INTERFACE configuration..."
-modules_conf --set PARSER > /dev/null
-if [ $PARSER_PORT -ne $ADMIN_INTERFACE_PARSER_PORT ]; then
-    echo -e "ERROR\nParser port on ADMIN_INTERFACE and PARSER modules must be the same!"
-    return 1
-fi
-ping "$ADMIN_INTERFACE_PARSER_IP" -c 1 &> /dev/null
-if [ $? -ne 0 ]; then
-    echo -e "ERROR\nInvalid IP address $ADMIN_INTERFACE_PARSER_IP!"
-    return 1
-fi
-echo "OK"
 add_to_list_var ADMIN_INTERFACE CHECKED_MODULES
+echo "OK"
 return 0
 }
 # END OF check_ADMIN_INTERFACE_config
@@ -832,14 +702,11 @@ while [ "$1" != "" ]; do
     shift 1
 done
 echo -n "Testing install configuration..."
-if [ -f $CAMPSITE_REGISTER ]; then
-    grep -w $APP_NAME $CAMPSITE_REGISTER &> /dev/null
-    if [ $? -eq 0 ]; then
-	is_installed=true
-	if ! $ic_upgrade; then
-	    echo -e "ERROR\nThe name is already used by another installation of campsite.\nUse --upgrade parameter for upgrade."
-	    return 1
-	fi
+if [ -f "$OLD_CAMPSITE_REGISTER" ]; then
+    is_installed=true
+    if ! $ic_upgrade; then
+	echo -e "ERROR\nThe name is already used by another installation of campsite.\nUse --upgrade parameter for upgrade."
+	return 1
     fi
 fi
 echo "OK"
@@ -921,110 +788,31 @@ return $result
 set_module_config()
 {
 module=$1
-output=`validate_module "$module" --config`
-if [ $? -ne 0 ]; then
-    echo "$output"
-    return 1
-fi
-tmp_file=".$$.modules.conf"
-> $tmp_file
-state=init
-while true; do
-    read -r line
-    if [ "$line" = "" ]; then
-	break
+module_file=`cd "$INSTALL_CONF"; php module_conf_file.php "$module"`
+tmp_file=".$$.$module_file"
+module_name=`echo "$module_file" | cut -f 1 -d "_"`
+if [ "$module_name" != "install" ]; then
+    output=`validate_module "$module" --config`
+    if [ $? -ne 0 ]; then
+	echo "$output"
+	return 1
     fi
-    case $state in
-    init)
-	module_name=""
-	inner_state=init
-	for w in $line; do
-	    case $inner_state in
-	    init)
-		if [ "$w" = "[" ]; then
-		    state=read_module_name
-		    inner_state=read_module_name
-		else
-		    echo $line >> $tmp_file
-		    break
-		fi ;;
-	    read_module_name)
-		module_name=$w
-		echo -e "[\n$module_name" >> $tmp_file
-		state=read_attr
-		break ;;
-	    *)
-		echo "Internal error; invalid state $inner_state"
-		rm -f $tmp_file
-		exit 1 ;;
-	    esac
-	done ;;
-    read_module_name)
-	for w in $line; do
-	    module_name=$w
-	    echo -e "[\n$module_name" >> $tmp_file
-	    state=read_attr
-            break
-	done ;;
-    read_attr)
-	i=1
-	fw=""
-	for w in $line; do
-	    if [ $i -eq 1 ]; then
-		fw=$w
-	    fi
-	    if [ "$w" = "]" ]; then
-		state=init
-		break
-	    fi
-	    i=`expr $i + 1`
-	done
-	if [ "$module_name" = "$module" ] && [ "$fw" != "]" ]; then
-	    attr_name=""
-	    attr_val=""
-	    attr_desc=""
-	    inner_state=attr_name
-	    for w in $line; do
-		case $inner_state in
-		attr_name)
-		    attr_name=$w
-		    inner_state=attr_val ;;
-		attr_val)
-		    if [ "$w" != "{" ]; then
-			attr_val="$attr_val $w"
-		    else
-			inner_state=attr_desc
-		    fi ;;
-		attr_desc)
-		    if [ "$w" = "}" ]; then
-			break
-		    elif [ "$w" != "{" ]; then
-			attr_desc="$attr_desc $w"
-		    fi ;;
-		*)
-		    echo "Internal error; invalid state $inner_state"
-		    rm -f $tmp_file
-		    exit 1 ;;
-		esac
-	    done
-	    real_attr_name="${module_name}_$attr_name"
-	    echo -e "$attr_name ${!real_attr_name}\t{$attr_desc }" >> $tmp_file
-	fi
-	if [ "$module_name" != "$module" ] && [ "$fw" != "]" ]; then
-	    echo "$line" >> $tmp_file
-	fi
-	if [ "$state" = "init" ]; then
-	    echo "]" >> $tmp_file
-	fi ;;
-    *)
-	echo "Internal error; invalid state $state"
-	rm -f $tmp_file
-	exit 1 ;;
-    esac
+fi
+module_vars=`cd "$INSTALL_CONF"; php export_module_params.php "$module"`
+echo -e "<?php\n" > $tmp_file;
+vars_list_str=""
+for var in $module_vars; do
+    echo -e "\$Campsite['$var'] = '${!var}';" >> $tmp_file;
+    if [ "$vars_list_str" = "" ]; then
+	vars_list_str="\"$var\"";
+    else
+	vars_list_str="$vars_list_str, \"$var\""
+    fi
 done
-cp -f $tmp_file ${INSTALL_CONF}/.modules.conf
-rm -f $tmp_file
-set_configured $module_name
+echo -e "\n\$campsite_local_vars['$module_name'] = array($vars_list_str);\n\n?>\n" >> $tmp_file;
+cp -f "$tmp_file" "${INSTALL_CONF}/$module_file"
+rm -f "$tmp_file"
+[ "$module_name" != "install" ] && set_configured $module_name
 return 0
 }
 # END OF set_module_config
@@ -1035,83 +823,9 @@ return 0
 # Variables set: none
 set_install_config()
 {
-tmp_file=".$$.install.conf"
-> $tmp_file
-state=init
-while true; do
-    read -r line
-    case $state in
-    init)
-	for w in $line; do
-	    if [ "$w" = "[" ]; then
-		echo "[" >> $tmp_file
-		state=read_attr
-	    fi
-	done
-	[ "$state" = "init" ] && echo "$line" >> $tmp_file
-	;;
-    read_attr)
-	i=1
-	fw=""
-	for w in $line; do
-	    if [ $i -eq 1 ]; then
-		fw=$w
-	    fi
-	    if [ "$w" = "]" ]; then
-		state=end
-		break
-	    fi
-	    i=`expr $i + 1`
-	done
-	if [ "$fw" != "]" ]; then
-	    attr_name=""
-	    attr_val=""
-	    attr_desc=""
-	    inner_state=attr_name
-	    for w in $line; do
-		case $inner_state in
-		attr_name)
-		    attr_name=$w
-		    inner_state=attr_val ;;
-		attr_val)
-		    if [ "$w" != "{" ]; then
-			attr_val="$attr_val $w"
-		    else
-			inner_state=attr_desc
-		    fi ;;
-		attr_desc)
-		    if [ "$w" = "}" ]; then
-			break
-		    elif [ "$w" != "{" ]; then
-			attr_desc="$attr_desc $w"
-		    fi ;;
-		*)
-		    echo "Internal error; invalid state $inner_state"
-		    rm -f $tmp_file
-		    exit 1 ;;
-		esac
-	    done
-	    echo -e "$attr_name ${!attr_name}\t{$attr_desc }" >> $tmp_file
-	fi
-	if [ "$state" = "end" ]; then
-	    echo "]" >> $tmp_file
-	fi ;;
-    end)
-	echo "$line" >> $tmp_file
-        break
-	;;
-    *)
-	echo "Internal error; invalid state $state"
-	rm -f $tmp_file
-	exit 1 ;;
-    esac
-done
-cp -f $tmp_file ${INSTALL_CONF}/.inst.conf
-rm -f $tmp_file
-INSTALL_CONFIGURED=yes
-return 0
+set_module_config install
+return 1
 }
-# END OF set_install_config
 
 ###########################################################
 ## Functions for user interface
@@ -1150,14 +864,14 @@ return 0
 # Variables set: none
 read_install_conf()
 {
-attr_list=`install_conf | cut -f 1 -d "#"`
-attr_name_list=""
-for a in $attr_list; do
-    attr_name=`echo $a | cut -f 1 -d "="`
-    attr_name_list="$attr_name_list $attr_name"
-    attr_val=`echo $a | cut -f 2 -d "="`
-    export $a
-    read_string $attr_name "$attr_val" "`install_conf | grep -w ^$attr_name | cut -f 2 -d "#"`"
+attr_name_list="`install_conf | cut -f 1 -d "="`"
+for attr_name in $attr_name_list; do
+    al="`install_conf | grep -w $attr_name`"
+    attr_val="`echo $al | cut -f 2 -d "=" | cut -f 1 -d "#"`"
+    attr_val="`echo $attr_val`"
+    attr_desc="`echo $al | cut -f 2 -d "#"`"
+    export $attr_name="$attr_val"
+    read_string $attr_name "$attr_val" "$attr_desc"
 done
 return 0
 }
@@ -1177,9 +891,10 @@ if [ $? -ne 0 ]; then
     echo "$output"
     return 1
 fi
-clear
+#clear
 echo "Current $module configuration:"
 modules_conf $module
+[ $? -ne 0 ] && return 1
 echo -e "\nSelect\t1 - to modify configuration\n\t0 - to exit"
 return 0
 }
@@ -1191,7 +906,7 @@ return 0
 # Variables set: none
 install_config_menu()
 {
-clear
+#clear
 echo "Current install configuration:"
 install_conf $module
 echo -e "\nSelect\t1 - to modify configuration\n\t0 - to exit"
@@ -1246,12 +961,13 @@ while true; do
 		    if [ $? -ne 0 ]; then
 			message=$output
 		    fi
+		    modules_conf --set PARSER
 		fi
 		break
 	    fi
 	done ;;
     0)
-	clear
+#	clear
 	message=""
 	return 0 ;;
     *)
@@ -1296,6 +1012,7 @@ while true; do
 		    if [ $? -ne 0 ]; then
 			message=$output
 		    fi
+		    install_conf --set
 		fi
 		break
 	    fi
@@ -1307,7 +1024,7 @@ while true; do
 	    echo "Invalid install configuration. Aborting..."
 	    return 1
 	fi
-	clear
+#	clear
 	message=""
 	return 0 ;;
     *)
diff --git a/campsite/.install_conf/install_functions b/campsite/.install_conf/install_functions
--- a/campsite/.install_conf/install_functions
+++ b/campsite/.install_conf/install_functions
@@ -2,97 +2,6 @@
 
 . ${INSTALL_CONF}/conf_functions
 
-select_modules()
-{
-modules_list=`modules_list`
-selected_modules=`selected_modules`
-err_msg=""
-saved=true
-clear
-[ "$1" != "" ] && echo $1
-while true; do
-    echo "Please select modules to be installed on this system."
-    echo "Modules marked with X are selected."
-    sm_index=1
-    for sm_mod in $modules_list; do
-	echo -n -e "\t$sm_index. ["
-	if in_list $sm_mod $selected_modules; then echo -n "X"
-	else echo -n " "; fi
-	echo "] $sm_mod"
-	sm_index=`expr $sm_index + 1`
-    done
-    sm_index=`expr $sm_index - 1`
-    echo -e "\nMenu"
-    echo -e "\t1. Select a module"
-    echo -e "\t2. Deselect a module"
-    echo -e -n "\t3. Save module selection"
-    $saved && echo " (already saved)"
-    ! $saved && echo " (not saved)"
-    echo -e -n "\t0. Exit module selection"
-    $saved && echo ""
-    ! $saved && echo " (without saving)"
-    echo "$err_msg"
-    echo -n "Select a choice: "
-    read -r choice
-    if [ "$choice" != "0" ] && [ "$choice" != "1" ] && [ "$choice" != "2" ] && [ "$choice" != "3" ]; then
-	err_msg="Invalid choice $choice"
-    else
-	err_msg=""
-	case $choice in
-	0) break ;;
-	1)
-	    read_string module_number
-	    m_nr=$module_number
-	    if [ $m_nr -gt $sm_index ] || [ 0 -ge $m_nr ]; then
-		err_msg="Invalid module number $module_number"
-	    else
-		mod_name=`list_item $module_number $modules_list`
-		if in_list $mod_name $selected_modules; then
-		    err_msg="Module $mod_name already selected"
-		else
-		    sm_deps_on=`depends_on $mod_name`
-		    for sm_dep_on in $sm_deps_on; do
-			add_to_list_var $sm_dep_on selected_modules
-			err_msg="$mod_name depends on $sm_deps_on modules. They were selected too."
-		    done
-		    add_to_list_var $mod_name selected_modules
-		    saved=false
-		fi
-	    fi ;;
-	2)
-	    read_string module_number
-	    m_nr=$module_number
-	    if [ $m_nr -gt $sm_index ] || [ 0 -ge $m_nr ]; then
-		err_msg="Invalid module number $module_number"
-	    else
-		mod_name=`list_item $module_number $modules_list`
-		if ! in_list $mod_name $selected_modules; then
-		    err_msg="Module $mod_name already deselected"
-		else
-		    sm_deps_on=`dependent_on $mod_name`
-		    for sm_dep_on in $sm_deps_on; do
-			rm_from_list_var $sm_dep_on selected_modules
-			err_msg="$sm_deps_on modules depend on $mod_name. They were deselected too."
-		    done
-		    rm_from_list_var $mod_name selected_modules
-		    saved=false
-		fi
-	    fi ;;
-	3)
-	    rm -f $INSTALL_CONF/.inst.modules
-	    for sm_mod in $selected_modules; do
-		echo $sm_mod >> $INSTALL_CONF/.inst.modules
-	    done
-	    err_msg="Module selection was saved succesfully."
-	    saved=true ;;
-	esac
-    fi
-    clear
-done
-export SELECTED_MODULES=`selected_modules`
-set_need_config_modules
-}
-
 configure_campsite()
 {
 cc_upgrade=""
@@ -107,31 +16,12 @@ done
 
 if [ "$cc_interactive" = "--interactive" ]; then
 
-echo -e "\nCampsite application can be installed in two ways:"
-echo "1. single system: the whole application installed on a single system"
-echo -e "2. multiple system: modules of the application can be installed on different\n\t\tsystems\n"
-while true; do
-    read_string install_type 1 "1 - single system, 2 - multiple system"
-    if [ "$install_type" != "1" ] && [ "$install_type" != "2" ]; then
-	echo "Invalid choice $install_type"
-    else
-	break
-    fi
-done
-inst_type_msg="single system"
-[ $install_type -eq 2 ] && inst_type_msg="multiple system"
 echo -e "\nCampsite application is composed out of modules. Before installing"
 echo "campsite they must be configured."
-if [ $install_type -eq 2 ]; then
-    echo -e "\nSelecting multiple system installation you will be able to select the"
-    echo "modules to install on this system. Keep in mind that in the end all"
-    echo "campsite modules must be installed."
-else
-    rm -fr $INSTALL_CONF/.inst.modules
-    for cc_mod in `modules_list`; do
-	echo $cc_mod >> $INSTALL_CONF/.inst.modules
-    done
-fi
+rm -fr $INSTALL_CONF/.inst.modules
+for cc_mod in `modules_list`; do
+    echo $cc_mod >> $INSTALL_CONF/.inst.modules
+done
 echo ""
 choice_yn "Do you want to read the description of campsite modules?" N
 if [ "$choice" = "Y" ]; then
@@ -142,9 +32,6 @@ if [ "$choice" = "Y" ]; then
     read
     clear
 fi
-if [ $install_type -eq 2 ]; then
-    select_modules
-fi
 
 fi # interactive
 
@@ -153,43 +40,27 @@ check_install_deps || exit 1
 check_install_config $cc_upgrade
 if $is_installed && [ "$cc_upgrade" != "--upgrade" ]; then
     [ "$cc_interactive" != "--interactive" ] && exit 1
-    echo "There is another campsite application instance ($APP_NAME) already installed."
+    echo "There is another older campsite instance already installed."
     choice_yn "Do you want to upgrade the current installation?" Y
     if [ "$choice" = "Y" ]; then
 	cc_upgrade=--upgrade
 	export upgrade=--upgrade
-	modules_conf --set
+	modules_conf --set || return 1
     else
 	echo "Installing new instance of campsite..."
-    fi
-    export OLD_VERSION=`grep -w $APP_NAME /etc/campsite.reg | cut -f 2 -d ":"`
-    echo "$OLD_VERSION" > $INSTALL_CONF/../.old_version
-fi
-b_upgrade=false
-[ "$cc_upgrade" = "--upgrade" ] && b_upgrade=true
-if [ "$cc_interactive" = "--interactive" ] && ( ! $is_installed || ! $b_upgrade ); then
-    configure_install $cc_upgrade
-    [ $? -ne 0 ] && echo "Error setting campsite instance name" && exit 1
-    install_conf --set
-    . $INSTALL_CONF/../configure --define_start_env &> /dev/null
-fi
-if [ "$cc_upgrade" = "--upgrade" ]; then
-    $INSTALL_CONF/read_app_conf
-    result=$?
-    if [ $result -ne 0 ]; then
-    echo result $result
-	choice_yn "Error reading $APP_NAME configuration. Continue anyway?" Y
-	if [ "$choice" = "N" ]; then
-	    echo "Aborting..."
-	    exit 1
-	fi
     fi
 fi
 
 if [ "$cc_interactive" = "--interactive" ]; then
 
+configure_install $cc_upgrade
+[ $? -ne 0 ] && echo "Error configuring install parameters" && exit 1
+install_conf --set
+. $INSTALL_CONF/../configure --define_start_env &> /dev/null
+
+export MODULES_LIST="DATABASE PARSER EVENT_HANDLERS SEARCH_ENGINE ADMIN_INTERFACE"
 echo "Please wait while checking modules configuration..."
-for cc_mod in $SELECTED_MODULES; do
+for cc_mod in $MODULES_LIST; do
     check_module_deps $cc_mod $cc_interactive
     if [ $? -ne 0 ]; then
 	if [ "$output" != "" ]; then echo $output; fi
@@ -206,11 +77,11 @@ for cc_mod in $NEED_CONFIG_MODULES; do
 	echo "Aborting..."
 	exit 1
     fi
-    check_${cc_mod}_config $cc_interactive
+    check_${cc_mod}_config $cc_interactive || exit 1
 done
 cc_err_msg=""
 while true; do
-    clear
+#    clear
     echo "The forward list shows modules that need to be configured."
     echo "Modules checked with X have a valid configuration."
     cc_index=1
@@ -265,6 +136,7 @@ if [ "$choice" = "Y" ]; then
     for cc_mod in $NEED_CONFIG_MODULES; do
 	echo "$cc_mod configuration:"
 	modules_conf $cc_mod
+	[ $? -ne 0 ] && return $?
 	echo -e "\nTo continue press ENTER"
 	read
     done
