create config.php file (contains server IP address, server port, script base)

diff --git a/implementation/management/root/configure b/implementation/management/root/configure
--- a/implementation/management/root/configure
+++ b/implementation/management/root/configure
@@ -10,11 +10,25 @@ database_vars="DATABASE_SERVER DATABASE_USER DATABASE_PASSWORD DATABASE_NAME"
 var_not_modified $database_vars && [ -f db_connect.php ] && exit 0
 save_var $database_vars
 
-echo -n -e "\tWriting db_connect.php..."
+echo -n -e "\t\tWriting db_connect.php..."
 cat > db_connect.php << EOF
 <?php
 mysql_connect("$DATABASE_SERVER", "$DATABASE_USER", "$DATABASE_PASSWORD");
 mysql_select_db("$DATABASE_NAME");
+?>
+EOF
+[ $? -ne 0 ] && echo "ERROR" && exit 1
+echo OK
+chmod o-rwx db_connect.php
+
+
+echo -n -e "\t\tWriting config.php..."
+cat > config.php << EOF
+<?php
+\$SERVER_ADDRESS = "$ADMIN_INTERFACE_PARSER_IP";
+\$SERVER_PORT = "$ADMIN_INTERFACE_PARSER_PORT";
+\$SERVER_DEFAULT_PORT = "$PARSER_DEFAULT_PORT";
+\$scriptBase='$ADMIN_INTERFACE_SCRIPT_DIR';
 ?>
 EOF
 [ $? -ne 0 ] && echo "ERROR" && exit 1
