changes to allow installation without root password

diff --git a/campsite/implementation/parser/parser/install_parser b/campsite/implementation/parser/parser/install_parser
--- a/campsite/implementation/parser/parser/install_parser
+++ b/campsite/implementation/parser/parser/install_parser
@@ -25,6 +25,10 @@
 #
 ################################################################################
 
+mkdir -p $CONF_DIR
+echo -e "THREADS $PARSER_THREADS\nPORT $PARSER_PORT\nALLOWED_HOSTS $PARSER_ALLOWED_HOSTS\nUSER $PARSER_USER\nGROUP $PARSER_GROUP\n" > ${CONF_DIR}/parser.conf
+[ $? -ne 0 ] && echo "Error writing parser configuration file" && exit 1
+
 mkdir -p $BIN_DIR
 echo "Stop old version server (if installed)"
 test -f $BIN_DIR/$CAMPSITECTL && $BIN_DIR/$CAMPSITECTL stop
@@ -36,6 +40,9 @@ chmod +s $BIN_DIR/$CAMPSITE_SERVER
 cp -f $CAMPSITECTL $BIN_DIR
 chown ${ROOT_USER}.${ROOT_GROUP} ${BIN_DIR}/$CAMPSITECTL
 chmod 755 $BIN_DIR/$CAMPSITECTL
+
+if $USER_INSTALL; then exit 0; fi
+
 if [ -d $RC_INIT ]; then
 	cp -f $CAMPSITEINIT $RC_INIT
 	chown ${ROOT_USER}.${ROOT_GROUP} ${RC_INIT}/$CAMPSITEINIT
@@ -55,7 +62,5 @@ elif [ -d /etc/rc.d ]; then
 		[ $? -ne 0 ] && echo "ERROR installing start/stop script" && exit 1
 	fi
 fi
-mkdir -p $CONF_DIR
-echo -e "THREADS $PARSER_THREADS\nPORT $PARSER_PORT\nALLOWED_HOSTS $PARSER_ALLOWED_HOSTS\nUSER $PARSER_USER\nGROUP $PARSER_GROUP\n" > ${CONF_DIR}/parser.conf
-[ $? -ne 0 ] && echo "Error writing parser configuration file" && exit 1
+
 exit 0
